name:  Application deployment
on:
  deployment:

jobs:
  check-environment:
    runs-on: ubuntu-latest
    env:
      environments-matrix: "[\"tw-dev\", \"tw-staging\", \"tw-prod\"]"
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
      full-environment: ${{ steps.set-environment.outputs.full-environment }}
    steps:
      - name: Set Environment
        id: set-environment
        if: ${{ contains(fromJson(env.environments-matrix), github.event.deployment.environment) }}
        uses: actions/github-script@v3
        with:
          script: |
            const environment = context.payload.deployment.environment.split("-", 1);
            const envMap = { 'dev': 'development', 'staging': 'staging', 'prod': 'production' };
            let fullEnvironment = envMap[environment];
            core.setOutput('environment', environment);
            core.setOutput('full-environment', fullEnvironment);

    display-context:
      needs: [check-environment]
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo "${{ needs.check-environment.outputs.environment }}"
            echo "${{ needs.check-environment.outputs.full-environment }}"
